### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by cwgoes** [cwgoes/snarky-workshop#1]
- [ ] Test the sparse Merkle tree (once records or tuples work)
- [ ] Implement some sort of signature verification (possibly Schnorr signatures)
- [ ] Implement trivial UTXO system on top of key-value store
- [ ] Try to implement interaction nets using key-value store as memory

for UTXOs we can just treat knowledge of a hash pre-image as ownership of funds stored under the hash

cc @mariari
